stages:
 - build
 - test
 - sonar
 - release
 - notify

variables:
   VERSION: 1.0.${CI_PIPELINE_ID}

include:
   #- template: Security/SAST.gitlab-ci.yml
   - local: '/.gitlab-ci/.backend.yml'
   - local: '/.gitlab-ci/.frontend.yml'
   #- local: '/.gitlab-ci/.SAST.yml'
   #- local: '/.gitlab-ci/.sonarqube.yml'