stages:
 - build
 - test
 - notify

variables:
  CONTENT_TYPE: "Content-type: application/json"

include:
   - local: '/ci-templates/.backend.yml'
   - local: '/ci-templates/.frontend.yml'
   - template: Security/SAST.gitlab-ci.yml
   - local: '/ci-templates/.SAST.yml'

.sast_template: &sast_config
  rules:
    - if:
      changes:
      - backend/*
      - frontend/*