
before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 600 ~/.ssh

stages:
  - deploy

deploy:
  stage: deploy
  script:
     - ssh student@84.252.128.3 "id"

#stages:
#   - module-pipelines

#variables:
#   VERSION: 1.0.${CI_PIPELINE_ID}
#   JAVA_OPTS: -XX:MaxRAMPercentage=90

#frontend:
#   stage: module-pipelines
#   trigger:
#      include:
#         - local: "/.gitlab-ci/.frontend.yml"
#      strategy: depend
#   only:
#      changes:
#         - frontend/**/*

#backend:
#   stage: module-pipelines
#   trigger:
#      include:
#         - local: "/.gitlab-ci/.backend.yml"
#      strategy: depend
#   only:
#      changes:
#         - backend/**/*

#include:
#- local: '/.gitlab-ci/.backend.yml'
#- local: '/.gitlab-ci/.frontend.yml'
#- template: Security/SAST.gitlab-ci.yml
#- local: '/.gitlab-ci/.SAST.yml'
#- local: '/.gitlab-ci/.sonarqube.yml'
