version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-009-060/sausage-store/sausage-backend:latest
    pull_policy: always
    profiles: ["backend-only"]
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=sausage-backend
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_DATASOURCE_URL
      - SPRING_DATA_MONGODB_URI
      - SPRING_FLYWAY_ENABLED
      - REPORT_PATH
    networks:
      - sausage-network

  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-009-060/sausage-store/sausage-backend-report:latest
    pull_policy: always
    container_name: sausage-backend-report
    profiles: ["backend-report-only"]
    environment:
      - DB
    networks:
      - sausage-network

  frontend:
    image: gitlab.praktikum-services.ru:5050/std-009-060/sausage-store/sausage-frontend:latest
    pull_policy: always
    container_name: sausage-frontend
    profiles: ["frontend-only"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./frontend/nginx.tmpl:/app/nginx.tmpl
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/usr/share/nginx/html
    networks:
      - sausage-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    profiles: ["certbot-only"]
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/usr/share/nginx/html
    command: >
      certonly
      --webroot --webroot-path=/usr/share/nginx/html
      --email batckov.yury@yandex.ru --agree-tos --no-eff-email --force-renewal
      -d batkovy-glava82-sausagestore.tk -d www.batkovy-glava82-sausagestore.tk
    networks:
      - sausage-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  sausage-network:
    name: sausage-network