version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-009-060/sausage-store/sausage-backend:latest
    pull_policy: always
    profiles: ["backend-only"]
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=sausage-backend
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_DATASOURCE_URL
      - SPRING_DATA_MONGODB_URI
      - SPRING_FLYWAY_ENABLED
      - REPORT_PATH
    networks:
      - sausage-network
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-009-060/sausage-store/sausage-backend-report:latest
    pull_policy: always
    container_name: sausage-backend-report
    profiles: ["backend-report-only"]
    environment:
      - DB
    networks:
      - sausage-network
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-009-060/sausage-store/sausage-frontend:latest
    pull_policy: always
    container_name: sausage-frontend
    profiles: ["frontend-only"]
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/app/nginx.tmpl
      #- ./certs:/etc/nginx/certs:ro
      #- ./vhost.d:/etc/nginx/vhost.d
    networks:
      - sausage-network

#networks:
#  sausage-store:
networks:
  sausage-network:
    name: sausage-network