version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-009-060/sausage-store/sausage-backend:latest
    container_name: sausage-backend
    profiles: ["backend-only"]
    #env_file:
    #  - .backend.env
    # add variables from the docker-compose environment to the container:
    environment:
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_DATASOURCE_URL
      - SPRING_DATA_MONGODB_URI
      - SPRING_FLYWAY_ENABLED
      - REPORT_PATH
    networks:
      - sausage-store
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-009-060/sausage-store/sausage-backend-report:latest
    container_name: sausage-backend-report
    profiles: ["backend-report-only"]
    #env_file:
    #  - .backend-report.env
    environment:
      - DB
    networks:
      - sausage-store
    #depends_on:
    #  - backend
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-009-060/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    profiles: ["frontend-only"]
    ports:
      - "80:80"
    networks:
      - sausage-store
    #depends_on:
    #  - backend

networks:
  sausage-store:
