include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

stages:
   - build
   - deploy
   - notify

#build-backend-report:
#  stage: build
#  image:
#    name: gcr.io/kaniko-project/executor:v1.9.1-debug
#    entrypoint: [""]
#  variables:
#    CACHE_TTL: 2190h0m0s # three months
#    IMAGE_NAME: sausage-backend-report
#    CONTEXT: "${CI_PROJECT_DIR}/backend-report"
#  script:
#    - >
#      /kaniko/executor
#      --build-arg VERSION=$VERSION
#      --context "${CONTEXT}/"
#      --dockerfile "${CONTEXT}/Dockerfile"
#      --destination "${CI_REGISTRY_IMAGE}/$IMAGE_NAME:$VERSION"
#      --destination "${CI_REGISTRY_IMAGE}/$IMAGE_NAME:latest"
#      --cache=true
#      --cache-repo ${CI_REGISTRY_IMAGE}/$IMAGE_NAME
#      --cache-ttl $CACHE_TTL

deploy-backend-report:
  stage: deploy
  image: vault:1.12.1
  script:
    - apk add openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 600 ~/.ssh
    - ssh-keyscan ${DEV_HOST} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=sausage-store jwt=$CI_JOB_JWT)"

    - scp ./docker-compose.yml ${DEV_USER}@${DEV_HOST}:/home/${DEV_USER}/docker-compose.yml

    - >
      ssh ${DEV_USER}@${DEV_HOST}
      "export MONGO_USER=$(vault kv get -field=mongo.username secret/sausage-store);
       export MONGO_PASSWORD=$(vault kv get -field=mongo.password secret/sausage-store);
       export DB="mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?${MONGO_URI_SETTINGS_REPORT}";
      docker compose --file ~/docker-compose.yml --profile backend-report-only up --pull=always --detach --force-recreate backend-report"

slack-notification-backend:
  stage: notify
  only:
    variables:
      - '$CI_COMMIT_MESSAGE =~ /send notification/'
  script:
    - |-
        DATA=$(cat << JSON
        {
          "text":"YB - Вышла новая версия backend сосисочной — ${VERSION}. Скачать backend можно по ссылке — <${NEXUS_REPO_URL}/repository/09-sausage-store-batkov-yuriy-backend/com/yandex/practicum/devops/sausage-store/${VERSION}/sausage-store-${VERSION}.jar|Backend ${VERSION}>"
        }
        JSON
        )
    #- echo "$DATA"
    #- >
    #  curl
    #  --request POST
    #  --header "Content-type: application/json"
    #  --data "${DATA}"
    #  "${SLACK_WEBHOOK}"
