
build-backend-code-job:
  stage: build
  rules:
    - changes:
      - backend/*
  script:
    - echo JOB_ID_BACK=$CI_JOB_ID >> back.env
    - cd backend
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
  artifacts:
    reports:
      dotenv: back.env
    paths:
      - ${CI_PROJECT_DIR}/.m2/
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar

slack-notification-backend:
  stage: notify
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /send notification/'
      changes:
      - backend/*
  variables:
    DATA: '{"text":"Юрий Батков собрал backend. \n <${CI_PROJECT_URL}/-/jobs/${JOB_ID_BACK}/artifacts/download|Backend Artifact>"}'
  script:
    - echo "$DATA"
    #
    #- >
    #  curl
    #  --request POST
    #  --header "Content-type: application/json"
    #  --data "${DATA}"
    #  "${SLACK_WEBHOOK}"
