
build-backend:
  stage: build
  rules:
    - changes:
      - backend/**/*
  script:
    - echo JOB_ID_BACK=$CI_JOB_ID >> back.env
    - cd backend
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
  artifacts:
    reports:
      dotenv: back.env
    paths:
      - ${CI_PROJECT_DIR}/.m2/
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar

slack-notification-backend:
  stage: notify
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /send notification/'
      changes:
      - backend/**/*
  script:
    - |-
        DATA=$(cat << JSON
        {
          "text":"Юрий Батков собрал backend. <${CI_PROJECT_URL}/-/jobs/${JOB_ID_FRONT}/artifacts/download|Backend Artifact>"
        }
        JSON
        )
    - echo "$DATA"
    #
    #- >
    #  curl
    #  --request POST
    #  --header "Content-type: application/json"
    #  --data "${DATA}"
    #  "${SLACK_WEBHOOK}"
