
build-frontend:
  stage: build
  rules:
    - changes:
      - frontend/*
  script:
    - echo JOB_ID_FRONT=$CI_JOB_ID >> front.env
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    reports:
      dotenv: front.env
    paths:
      - frontend/dist/frontend

# TODO:
# 1. implement generic notification templates
# 2. implement failed\success notifications (depends on test results)
# 3. implement cool slack message template

slack-notification-frontend:
  stage: notify
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /send notification/'
      changes:
      - backend/*
  script:
    - |-
        DATA=$(cat << JSON
        {
          "text":"Юрий Батков собрал frontend. <${CI_PROJECT_URL}/-/jobs/${JOB_ID_FRONT}/artifacts/download|Frontend Artifact>"
        }
        JSON
        )
    - echo "$DATA"
    #
    #- >
    #  curl
    #  --request POST
    #  --header "Content-type: application/json"
    #  --data "${DATA}"
    #  "${SLACK_WEBHOOK}"
