
spotbugs-sast:
  rules:
    - changes:
      - backend/*
  needs:
    - build-backend
  variables:
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: $CI_PROJECT_DIR/.m2/repository
    COMPILE: "false"
  artifacts:
    reports:
      sast: gl-sast-report.json

eslint-sast:
  rules:
    - changes:
      - frontend/*
  needs:
    - build-frontend

nodejs-scan-sast:
  rules:
    - changes:
      - frontend/*
  needs:
    - build-frontend

semgrep-sast:
  rules:
    - changes:
      - frontend/*
      - backend/*
  needs:
    - build-frontend
    - build-backend