
spotbugs-sast:
  dependencies:
    - build-backend-code-job
  variables:
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: $CI_PROJECT_DIR/.m2/repository
    COMPILE: "false"
  rules:
    - changes:
      - backend/*
  artifacts:
    reports:
      sast: gl-sast-report.json

eslint-sast:
  rules:
    - changes:
      - frontend/*

nodejs-scan-sast:
  rules:
    - changes:
      - frontend/*

semgrep-sast:
  rules:
    - changes:
      - frontend/*
      - backend/*