
build-frontend-code-job:
  stage: build
  only:
    changes:
    - frontend/*
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/frontend

slack-notification-frontend:
  stage: notify
  only:
    changes:
    - frontend/*
    variables:
    - $CI_COMMIT_MESSAGE =~ /send notification/
  variables:
    DATA: '{"text":"Юрий Батков собрал frontend. \n <${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_REF_NAME}/download?job=build-frontend-code-job|Fronteend Artifact>"}'
  script:
    - curl -X POST -H "${CONTENT_TYPE}" --data "${DATA}" "${SLACK_WEBHOOK}"
  needs:
    - build-frontend-code-job